using SharedMethods;
using System;
using System.Data;
using System.Data.SqlClient;
using System.Windows.Forms;

namespace UsersAndAssetsV2
{
    /// <summary>
    /// Represents the form used for entering or editing YubiKey data.
    /// </summary>
    public partial class FormYubiKeysEntry : Form
    {
        private readonly int AssetID;
        private readonly int DepartmentID;
        private readonly bool IsEdit;           // Indicates if the form is in edit mode
        private readonly string PublicId;       // The ID generated by the YubiKey configuration software
        private readonly string SerialNumber;   // The YubiKey serial number
        private readonly SqlConnection SqlConn; // SQL connection used for database operations
        private readonly int YubiKeyId;         // The record number from the YubiKey database

        public FormYubiKeysEntry(SqlConnection sqlConn)
        {
            InitializeComponent();

            IsEdit = false; 
            PublicId = string.Empty;
            SerialNumber = string.Empty;
            SqlConn = sqlConn;
        }

        public FormYubiKeysEntry(DataRow row, SqlConnection sqlConn)
        {
            InitializeComponent();

            AssetID = (int)row.Field<object>("AssetID");
            DepartmentID = (int)row.Field<object>("DeptID");
            IsEdit = true;
            PublicId = row.Field<object>("PublicID").ToString();
            SerialNumber = row.Field<object>("Serial").ToString();
            SqlConn = sqlConn; 
            YubiKeyId = (int)row.Field<object>("ID");
        }

        private void FormYubiKeysEntry_Load(object sender, EventArgs e)
        {
            this.Icon = System.Drawing.Icon.ExtractAssociatedIcon(Application.ExecutablePath);
            this.StartPosition = FormStartPosition.CenterParent;

            PopulateCboAssetType();
            PopulateCboDepartment();

            if (IsEdit) PopulateFormFields();
        }

        #region Hide the closing 'X'

        private const int CP_NOCLOSE_BUTTON = 0x200;
        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams myCp = base.CreateParams;
                myCp.ClassStyle |= CP_NOCLOSE_BUTTON;
                return myCp;
            }
        }

        #endregion

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.Cancel;
            this.Close(); // Close the form
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            bool validForm = VerifyFormData();
            if (validForm)
            {
                SaveYubiKeyRecord();

                this.DialogResult = DialogResult.OK;
                this.Close(); // Close the form
            }
            else
            {
                MessageBox.Show("Please enter the required items."); // Show validation message
            }
        }

        private void cboDepartment_DropDown(object sender, EventArgs e)
        {
            cboDepartment.SelectedIndex = -1;
        }

        #region General Methods

        private void PopulateCboAssetType()
        {
            string query = "SELECT [ID], [Description] FROM [AssetType] WHERE [Description] LIKE 'YubiKey%' ORDER BY [Description];";
            PopulateComboBox(cboAssetType, query, "ID", "Description");
        }

        private void PopulateCboDepartment()
        {
            string query = "SELECT [ID], [Name] FROM [Department] ORDER BY [Name];";
            PopulateComboBox(cboDepartment, query, "ID", "Name");
        }

        private void PopulateComboBox(ComboBox comboBox, string query, string valueItem, string displayItem)
        {
            comboBox.Items.Clear();
            DatabaseMethods.PopulateComboBoxUsingObjectFields(comboBox, query, valueItem, displayItem, SqlConn);
            comboBox.SelectedIndex = -1;
        }

        private void PopulateFormFields()
        {
            cboDepartment.SelectedValue = DepartmentID.ToString();
            cboAssetType.SelectedValue = AssetID.ToString();
            txtPublicId.Text = PublicId.Trim();
            txtSerialNumber.Text = SerialNumber.Trim();
        }

        /// <summary>
        /// Saves the YubiKey record to the database. It either inserts a new record or updates an existing one based on the form's mode (edit or new).
        /// </summary>
        private void SaveYubiKeyRecord()
        {
            // Extract the form values
            int assetTypeId = Convert.ToInt32(cboAssetType.SelectedValue);
            int departmentId = Convert.ToInt32(cboDepartment.SelectedValue);
            string publicId = txtPublicId.Text.Trim();
            string serialNumber = txtSerialNumber.Text.Trim();

            // Define the SQL query based on whether it's an update or insert
            string query;
            if (IsEdit)
            {
                query = @"
                    UPDATE [YubiKey] 
                    SET [SerialNumber] = @SerialNumber,
                        [PublicID] = @PublicID,
                        [AssetType_ID] = @AssetTypeID,
                        [Department_ID] = @DepartmentID
                    WHERE [ID] = @YubiKeyID;";
            }
            else
            {
                query = @"
                    INSERT INTO [YubiKey] 
                        ([SerialNumber], [PublicID], [AssetType_ID], [Department_ID])
                    VALUES 
                        (@SerialNumber, @PublicID, @AssetTypeID, @DepartmentID);";
            }

            try
            {
                // Execute the SQL query with parameters
                ExecuteNonQuery(query, command =>
                {
                    command.Parameters.AddWithValue("@AssetTypeID", assetTypeId);
                    command.Parameters.AddWithValue("@DepartmentID", departmentId);
                    command.Parameters.AddWithValue("@PublicID", publicId);
                    command.Parameters.AddWithValue("@SerialNumber", serialNumber);
                    if (IsEdit) command.Parameters.AddWithValue("@YubiKeyID", YubiKeyId);
                });
            }
            catch (SqlException ex)
            {
                CommonMethods.DisplayError($"An error occurred while saving the record: {ex.Message}", "Database Error");
            }
        }

        /// <summary>
        /// Executes a SQL query with parameters, managing the SQL connection automatically.
        /// </summary>
        /// <param name="query">The SQL query to execute.</param>
        /// <param name="setParameters">An action that adds the necessary SQL parameters to the command.</param>
        private void ExecuteNonQuery(string query, Action<SqlCommand> setParameters)
        {
            using (SqlCommand command = new SqlCommand(query, SqlConn))
            {
                setParameters(command);
                SqlConn.Open();
                command.ExecuteNonQuery();
                SqlConn.Close();
            }
        }

        private bool VerifyFormData()
        {
            // Check for missing fields and provide feedback in one message
            string errorMessage = "";

            if (cboAssetType.SelectedIndex == -1)
            {
                errorMessage += "Please select a valid Asset Type.\n";
                cboAssetType.Focus();
            }

            if (cboDepartment.SelectedIndex == -1)
            {
                errorMessage += "Please select a valid Department.\n";
                cboDepartment.Focus();
            }

            if (string.IsNullOrWhiteSpace(txtPublicId.Text))
            {
                errorMessage += "Please enter the Public ID.\n";
                txtPublicId.Focus();
            }

            if (string.IsNullOrWhiteSpace(txtSerialNumber.Text))
            {
                errorMessage += "Please enter the Serial Number.\n";
                txtSerialNumber.Focus();
            }

            if (!string.IsNullOrEmpty(errorMessage))
            {
                MessageBox.Show(errorMessage, "Validation Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }

            return true;
        }

        #endregion
    }
}
